title: GitHubの練習をしてるページ
author: Katsuharu Negishi
email: katsu.negishi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 # social links
twitter_username:　@bonbalabonba # DO NOT include the @ character, or else the build will fail!
github_username:  katsuhaa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
